### ISSUE TITLE
Zod shapes no longer generated for status codes 201 - 399

### ISSUE THREAD

**Issue by NimmLor** [kubb-project/kubb#826]
### What version of `kubb` is running?

2.6.1, 2.6.2, 2.6.3

### What platform is your computer?

Windows 11

### What steps can reproduce the bug?

Upon upgrading from v2.5.3 to v2.6.1 kubb no longer generates zod shapes for responses with statuscodes 201-399. 

1. Add @kubb/swagger-zod as plugin
2. Create a '201' response
3. Ref some component in the '201' response
4. Run kubb generate
The example spec generates:

```diff
diff --git v2.5.3 v2.6.2

import { z } from 'zod'
import { createUserResultSchema } from './createUserResultSchema'

export const createUserSchema = z.object({
  email: z.string().email().optional(),
})
export const createUserMutationRequestSchema = z.object({ name: z.string() })

+ export const createUserMutationResponseSchema = z.any()
- /**
-  * @description OK
-  */
- export const createUser201Schema = z.lazy(() => createUserResultSchema)
- export const createUserMutationResponseSchema = z.lazy(
-   () => createUserResultSchema
- )

```

### How often does this bug happen?

Every time

### What is the expected behavior?

Schemas should be generated as in v2.5.3

### Swagger/OpenAPI file?

<details><summary>openapi.yml</summary>
<p>

```yml
components:
  schemas:
    CreateUser:
      properties:
        email:
          type: string
    CreateUserResult:
      properties:
        success:
          type: boolean
      required:
        - success
      type: object
info:
  license:
    name: MIT
  title: Kubb Sample
  version: 1.0.0
openapi: '3.0.0'
paths:
  /pets:
    post:
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResult'
          description: OK
``` 

</p>
</details>

**Comment by stijnvanhulle** [comment]
Should be resolved with version `2.6.3`

**Comment by NimmLor** [comment]
@stijnvanhulle Unfortunatly the example still doesn't generate it. Same as in 2.6.1/2.6.2

**Comment by NimmLor** [comment]
Hi,
2.6.4 now generates the responses again :)

However, these 201-399 responses are no longer added in the zodios endpoints.

```diff
import { makeApi, Zodios } from "@zodios/core";
+ import { createUserMutationResponseSchema, createUserMutationRequestSchema } from "./zod/createUserSchema";
- import { createUserMutationResponseSchema, createUserMutationRequestSchema, createUser201Schema } from "./zod/createUserSchema";

export const endpoints = makeApi([
    {
        method: "post",
        path: "/pets",
        description: ``,
        requestFormat: "json",
        parameters: [
            {
                name: "CreateUserMutationRequest",
                description: ``,
                type: "Body",
                schema: createUserMutationRequestSchema
            }
        ],
        response: createUserMutationResponseSchema,
+       errors: [],
-       errors: [
-           {
-               status: 201,
-               description: `OK`,
-               schema: createUser201Schema
-           }
-       ],
    }
]);
export const getAPI = (baseUrl: string) => new Zodios(baseUrl, endpoints);
export const api = new Zodios(endpoints);
export default api;
```

Another improvement that could be made is to assign the status 200 response to `<operation>MutationResponseSchema`, currently that zod shape gets duplicated

**Comment by stijnvanhulle** [comment]
That the 201-399 responses are not added to `errors` of Zodios is normal. We should not have added those in the first place to errors because they are not errors.
